<config.mk

#Obtain the station radio for each contaminant distribution
results/stations_radios.pdf:	data/missing
	set -x
	mkdir -p `dirname $target`
 	Rscript bin/station_radio.R \
		--contaminants "data/missing" \
		--maps "data/09mun" \
		--out $target".build.pdf" \
		--cores $NT \
	&& mv $target".build.pdf" $target

