<config.mk

#Obtain the data_chart by week, for each contaminant under each station
results/%.RData: data/filtered/%.RData
	set -x
	mkdir -p `dirname $target`
 	Rscript bin/data_chart.R \
		--file $prereq \
		--vgm 'data/variograms/'$stem'.RData' \
		--out 'results/'$stem'.pdf' \
		--rdata $target'.build' \
		--cores $NT \
	&& mv $target'.build' $target

