<config.mk

# Obtain the centroid coordinates
results/%.RData: data/%
	set -x
	mkdir -p `dirname $target`
 	Rscript bin/centroids_neighborhood_level.R \
		--directory $prereq \
		--out $target".build" \
		--cores $NT \
	&& mv $target".build" $target

